#数据库配置
spring:
  datasource:
    #数据库连接地址
    url: jdbc:mysql://localhost:3306/hushang_ayi?serverTimezone=UTC
    #数据库用户名
    username: root
    #数据库密码
    password: root
    #数据库驱动地址
    driver-class-name: com.mysql.cj.jdbc.Driver

#开启debug日志监控SQL信息
logging:
  level:
    com:
      kiwi:
        hushang_ayi:
          mapper: debug