spring:
  #数据库配置
  datasource:
    #数据库连接地址
    #url: jdbc:mysql://47.100.176.61:3306/one_piece?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/one_piece?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    #数据库用户名
    username: root
    #数据库密码
    password: root
    #数据库驱动地址
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接配置
    tomcat:
      #最大空闲连接数
      max-idle: 5
      #最大连接数
      max-active: 10

  #配置可上传文件的最大容量
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#指定log4j2配置文件
logging:
  config: classpath:log4j2-spring.xml

#指定MyBatis映射xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml

#图片服务器所在IP
photo:
  photo_url: "http://www.kiwilovedaisy.com:8080/image/"
  photo_path: "/usr/local/image/"