#数据库配置
spring:
  datasource:
    #数据库连接地址
    url: jdbc:mysql://localhost:3306/hushang_ayi?serverTimezone=UTC
    #数据库用户名
    username: root
    #数据库密码
    password: root
    #数据库驱动地址
    driver-class-name: com.mysql.cj.jdbc.Driver

#指定log4j2配置文件
logging:
  config: classpath:log4j2-spring.xml

#指定MyBatis映射xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml